# Generated by Django 3.0.6 on 2020-05-11 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Runs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(help_text='Name of the game name (including Multiple)', max_length=200)),
                ('category', models.CharField(help_text='Name of the category (ie. any%, Recruit Em All)', max_length=200)),
                ('ruleset', models.CharField(help_text='Name of applicable rulesets ie. if Wonder Mail is permitted', max_length=200)),
                ('playerName', models.CharField(help_text='sr.c username of runner', max_length=200)),
                ('runTime', models.CharField(help_text='Format: *h *m *s', max_length=200)),
            ],
        ),
    ]
